env:
  commonjs: true
  es2021: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
rules: {
  comma-dangle: [error, always-multiline],
  eol-last: [error, always],
  indent: [error, 2],
  object-curly-spacing: [error, always],
  quotes: [error, single, { avoidEscape: true }],
  semi: [error, never],
  quote-props: [error, as-needed],
}
