name: Default workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci
      - run: npm run lint

  scan-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npx @eqworks/scan-env --strict
        env:
          GITHUB_TOKEN: ${{ secrets.CD_GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.CD_SLACK_TOKEN }}
          SLACK_CHANNEL: C04557DM64Q # channel #auto-project-updates

  commit-watch:
    runs-on: ubuntu-latest
    if: contains(github.event_name, 'pull_request') # only run on pull requests
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: npx @eqworks/commit-watch -b ${{ github.event.pull_request.base.sha }} -h ${{ github.event.pull_request.head.sha }} -v
